apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jibri-one
  labels:
    component: jibri
  namespace: jibri
spec:
  serviceName: jibri-one
  replicas: 5
  selector:
    matchLabels:
      component: jibri
  template:
    metadata:
      labels:
        component: jibri
    spec:
      nodeSelector:
        asound: alsa1
      hostAliases:
        - ip: 'jitsi server ip'
          hostnames:
            - meet.example.com
      securityContext:
        fsGroup: 63
      initContainers:
        - name: init-set
          image: itsmaniche18/init-container
          command: 
            - /tmp/copyfile.sh
          volumeMounts:
            - name: home-dir
              mountPath: /home/jibri
      containers:
        - name: jibri
          image: docker.io/itsmaniche18/jibri

          resources:
            limits:
              memory: '4G'
              cpu: '2'
            requests:
              memory: '2G'
              cpu: '1'
          envFrom:
            - configMapRef:
                name: jibri-env
          volumeMounts:
            - name: jibri-recorder
              mountPath: /config/recordings
            - name: jibri-logs
              mountPath: /config/logs
            - name: snd
              mountPath: /dev/snd
            - name: shm
              mountPath: /dev/shm
            - name: finalize-sh
              mountPath: /config/finalize.sh
              subPath: finalize.sh
            - name: home-dir
              mountPath: /home/jibri
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_BIND_SERVICE
                - SYS_ADMIN
      volumes:
        - name: jibri-recorder
          emptyDir: {}
        - name: jibri-logs
          emptyDir: {}
        - name: snd
          hostPath:
            path: /dev/snd
        - name: finalize-sh
          configMap:
            name: finalize-sh
            defaultMode: 0777
        - name: home-dir
          emptyDir: {}
        - name: shm
          hostPath:
            path: /dev/shm