apiVersion: v1
kind: ConfigMap
metadata:
  name: jibri-env
  namespace: jibri
data:
  XMPP_AUTH_DOMAIN: auth.meet.example.com 
  XMPP_INTERNAL_MUC_DOMAIN: internal.auth.meet.example.com
  XMPP_RECORDER_DOMAIN: recorder.meet.example.com
  XMPP_SERVER: meet.example.com
  XMPP_DOMAIN: meet.example.com
  JIBRI_XMPP_USER: jibri
  JIBRI_XMPP_PASSWORD: jibriauthpass
  JIBRI_BREWERY_MUC: JibriBrewery
  JIBRI_RECORDER_USER: recorder
  JIBRI_RECORDER_PASSWORD: jibrirecorderpass
  JIBRI_RECORDING_DIR: /config/recordings
  JIBRI_FINALIZE_RECORDING_SCRIPT_PATH: /config/finalize.sh
  JIBRI_STRIP_DOMAIN_JID: conference
  JIBRI_LOGS_DIR: /config/logs
  DISPLAY: :0
  TZ: Asia/Kathmandu